ARCHS = arm64
INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = SlimShady

SlimShady_FILES = Tweak.xm
SlimShady_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
