INSTALL_TARGET_PROCESSES = Tweetbot

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Tweetbot4Tip

Tweetbot4Tip_FILES = Tweak.xm
Tweetbot4Tip_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
