INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Runaway
Runaway_FILES = Tweak.xm
Runaway_CFLAGS = -fobjc-arc
ARCHS = armv7 arm64 arm64e

include $(THEOS_MAKE_PATH)/tweak.mk
