INSTALL_TARGET_PROCESSES = backboardd

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = OutOfSight14

OutOfSight14_FILES = Tweak.xm
OutOfSight14_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
